# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d46690163f3701de89a7627990476cbe400eee485b35a18e90cbbc47f4393d463cf382f10c0faacae40f93fdfc73725ff6d4e31abd3670fcec066e11a1f7bd90

test:
  secret_key_base: 03689bb7d24934c65b2f8899d0fd0397526da94520871987dfb6db7aecf8238e4bb60c07d72a35c692f6114ef72ddff77d4c22c25ea52f95563248631a4d4db4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
